import { useEffect, useState } from 'react';
import { useWebSocket } from './hooks/useWebSocket';
import { useApi } from './hooks/useApi';
import { useStore } from './context/store';
// Mock data generation removed - now handled by backend
import { useToast } from './context/ToastContext';
import { KeyboardShortcutsHelp, useKeyboardShortcuts } from './components/KeyboardShortcuts';
import MetricsBar from './components/MetricsBar';
import ChatPanel from './components/ChatPanel';
import GraphView from './components/GraphView';
import EventStream from './components/EventStream';
import StatsDashboard from './components/StatsDashboard';
import IncidentPanel from './components/IncidentPanel';
import TopologyView from './components/TopologyView';
import AlertConfigModal from './components/alerts/AlertConfigModal';
import GlossaryPanel from './components/GlossaryPanel';
import OnboardingModal from './components/OnboardingModal';
import PacketFlowIntro from './components/PacketFlowIntro';
import { Settings, BarChart3, List, MessageSquare, AlertTriangle, Network } from 'lucide-react';

function App() {
  // Startup animation state (shown on first load only)
  const [showIntro, setShowIntro] = useState(() => {
    // Check if intro has been shown in this session
    const introShown = sessionStorage.getItem('intro-shown');
    return !introShown;
  });
  
  const handleIntroComplete = () => {
    sessionStorage.setItem('intro-shown', 'true');
    setShowIntro(false);
  };
  
  useWebSocket();
  useApi();
  
  const { 
    mockMode, 
    toggleMockMode, 
    clearOldEvents, 
    filters, 
    setFilters, 
    resetFilters,
    userProfile,
    trackViewSwitch,
    inferCognitiveStyle,
    dismissTooltip
  } = useStore();
  const { showInfo } = useToast();
  
  const [showShortcutsHelp, setShowShortcutsHelp] = useState(false);
  const [showAlertConfig, setShowAlertConfig] = useState(false);
  const [showOnboarding, setShowOnboarding] = useState(false);
  
  // Check if onboarding should be shown on first launch
  useEffect(() => {
    if (!userProfile.learning_progress.onboarding_completed) {
      setShowOnboarding(true);
    }
  }, [userProfile.learning_progress.onboarding_completed]);
  
  // ADAPTIVE UI: Default view based on cognitive style or user preference
  const getDefaultView = (): 'events' | 'stats' | 'topology' => {
    // H3-01: Respect manual preference override
    if (userProfile.preferred_default_view !== 'auto') {
      return userProfile.preferred_default_view as 'events' | 'stats' | 'topology';
    }
    
    // H1-02: Adaptive behavior - infer from cognitive style
    if (userProfile.cognitive_style === 'wholist') {
      return 'topology'; // Wholists prefer global/spatial views
    } else if (userProfile.cognitive_style === 'analyst') {
      return 'events'; // Analysts prefer detailed lists
    }
    // Unknown or novice: default to events
    return 'events';
  };
  
  const [activeTab, setActiveTab] = useState<'events' | 'stats' | 'topology'>(getDefaultView());
  const [leftPanelTab, setLeftPanelTab] = useState<'chat' | 'incidents'>('chat');
  const [previousCognitiveStyle, setPreviousCognitiveStyle] = useState(userProfile.cognitive_style);

  // H1-02: Show notification when adaptive view changes (one-time per style change)
  useEffect(() => {
    const ADAPTIVE_VIEW_TOOLTIP_ID = 'adaptive-view-changed';
    
    // Check if cognitive style changed AND we haven't shown this notification for this style
    if (
      previousCognitiveStyle !== userProfile.cognitive_style &&
      userProfile.cognitive_style !== 'unknown' &&
      !userProfile.learning_progress.tooltips_dismissed.includes(ADAPTIVE_VIEW_TOOLTIP_ID) &&
      userProfile.preferred_default_view === 'auto' // Only show if in auto mode
    ) {
      const newView = getDefaultView();
      setActiveTab(newView);
      
      showInfo(
        'View Adjusted',
        "We've adjusted your view for efficiency — you can change this anytime in Settings.",
        false
      );
      
      dismissTooltip(ADAPTIVE_VIEW_TOOLTIP_ID);
      setPreviousCognitiveStyle(userProfile.cognitive_style);
    }
  }, [userProfile.cognitive_style, userProfile.preferred_default_view, previousCognitiveStyle, dismissTooltip, showInfo, userProfile.learning_progress.tooltips_dismissed]);

  // Track view switches for cognitive style inference
  const handleTabChange = (newTab: 'events' | 'stats' | 'topology') => {
    trackViewSwitch(activeTab, newTab);
    setActiveTab(newTab);
    
    // Periodically infer cognitive style
    if (userProfile.interaction_count > 0 && userProfile.interaction_count % 5 === 0) {
      inferCognitiveStyle();
    }
  };

  useEffect(() => {
    const interval = setInterval(() => {
      clearOldEvents(10 * 60 * 1000);
    }, 60000);

    return () => clearInterval(interval);
  }, [clearOldEvents]);
  
  // Mock data is now generated by backend - frontend just receives via WebSocket
  
  // Keyboard shortcuts
  useKeyboardShortcuts({
    onShowHelp: () => setShowShortcutsHelp(true),
    onFocusSearch: () => {
      // Focus the search input in FilterBar
      const searchInput = document.querySelector('input[placeholder*="Search"]') as HTMLInputElement;
      if (searchInput) {
        searchInput.focus();
        showInfo('Search focused', 'Start typing to filter events');
      }
    },
    onToggleAnomalies: () => {
      setFilters({ onlyAnomalies: !filters.onlyAnomalies });
      showInfo(
        filters.onlyAnomalies ? 'Showing all events' : 'Showing anomalies only',
        filters.onlyAnomalies ? 'All events visible' : 'Filtered to anomalies only'
      );
    },
    onClearFilters: () => {
      setFilters({ searchQuery: '', severities: [], protocols: [], ports: [], onlyAnomalies: false });
      showInfo('Filters cleared', 'All filters have been removed');
    },
    onResetFilters: () => {
      resetFilters();
      showInfo('Filters reset', 'Filters restored to default');
    },
    onNextEvent: () => {
      showInfo('Next event', 'Use arrow keys to navigate events');
    },
    onPreviousEvent: () => {
      showInfo('Previous event', 'Use arrow keys to navigate events');
    },
    onOpenEvent: () => {
      // This will be handled by EventStream
      showInfo('Open event', 'Click an event to see details');
    },
    onExport: () => {
      // Trigger export menu
      const exportButton = document.querySelector('[aria-label="Export events"]') as HTMLButtonElement;
      if (exportButton) {
        exportButton.click();
      }
    },
    onToggleMockMode: () => {
      toggleMockMode();
      showInfo(
        mockMode ? 'Mock mode disabled' : 'Mock mode enabled',
        mockMode ? 'Connecting to real backend' : 'Generating mock data'
      );
    },
    onOpenSettings: () => {
      // Trigger settings button in MetricsBar
      const settingsButton = document.querySelector('[aria-label="Notification settings"]') as HTMLButtonElement;
      if (settingsButton) {
        settingsButton.click();
      }
    },
    onToggleTab: () => {
      const tabs: Array<'events' | 'stats' | 'topology'> = ['events', 'stats', 'topology'];
      const currentIndex = tabs.indexOf(activeTab);
      const nextTab = tabs[(currentIndex + 1) % tabs.length];
      setActiveTab(nextTab);
      const tabNames = {
        events: 'Events view',
        stats: 'Statistics view',
        topology: 'Topology view'
      };
      showInfo(tabNames[nextTab], `Viewing ${tabNames[nextTab].toLowerCase()}`);
    },
    onToggleLeftPanel: () => {
      setLeftPanelTab(prev => prev === 'chat' ? 'incidents' : 'chat');
      showInfo(
        leftPanelTab === 'chat' ? 'Incidents panel' : 'Chat panel',
        leftPanelTab === 'chat' ? 'Viewing incident management' : 'Viewing AI chat'
      );
    },
    onOpenAlertConfig: () => {
      setShowAlertConfig(true);
      showInfo('Alert Configuration', 'Configure detection settings and rules');
    },
    onShowTopology: () => {
      setActiveTab('topology');
      showInfo('Network Topology', 'Viewing network topology graph');
    },
    isModalOpen: showShortcutsHelp || showAlertConfig,
  });

  // Show intro animation on first load
  if (showIntro) {
    return <PacketFlowIntro onComplete={handleIntroComplete} />;
  }

  return (
    <div className="h-screen flex flex-col bg-base">
      <MetricsBar />

      <div className="flex-1 flex min-h-0">
        <div className="w-[500px] border-r border-border flex flex-col">
          {/* Left Panel Tabs */}
          <div className="flex items-center border-b border-border bg-panel">
            <button
              onClick={() => setLeftPanelTab('chat')}
              className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                leftPanelTab === 'chat'
                  ? 'text-text border-info'
                  : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
              }`}
            >
              <MessageSquare className="w-4 h-4" />
              Chat
            </button>
            <button
              onClick={() => setLeftPanelTab('incidents')}
              className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                leftPanelTab === 'incidents'
                  ? 'text-text border-info'
                  : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
              }`}
            >
              <AlertTriangle className="w-4 h-4" />
              Incidents
            </button>
          </div>
          
          {/* Left Panel Content */}
          {leftPanelTab === 'chat' ? <ChatPanel /> : <IncidentPanel />}
        </div>

        <div className="flex-1 flex flex-col min-w-0">
          <div className="h-1/2 border-b border-border">
            <GraphView />
          </div>

          <div className="h-1/2">
            {/* Tab Header */}
            <div className="flex items-center border-b border-border bg-panel">
              <button
                onClick={() => handleTabChange('events')}
                className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                  activeTab === 'events'
                    ? 'text-text border-info'
                    : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
                }`}
              >
                <List className="w-4 h-4" />
                Events
                {userProfile.cognitive_style === 'analyst' && activeTab !== 'events' && (
                  <span className="ml-1 text-xs text-info">★</span>
                )}
              </button>
              <button
                onClick={() => handleTabChange('stats')}
                className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                  activeTab === 'stats'
                    ? 'text-text border-info'
                    : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
                }`}
              >
                <BarChart3 className="w-4 h-4" />
                Statistics
              </button>
              <button
                onClick={() => handleTabChange('topology')}
                className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                  activeTab === 'topology'
                    ? 'text-text border-info'
                    : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
                }`}
              >
                <Network className="w-4 h-4" />
                Topology
                {userProfile.cognitive_style === 'wholist' && activeTab !== 'topology' && (
                  <span className="ml-1 text-xs text-info">★</span>
                )}
              </button>
            </div>
            
            {/* Tab Content */}
            {activeTab === 'events' ? (
              <EventStream />
            ) : activeTab === 'stats' ? (
              <StatsDashboard />
            ) : (
              <TopologyView />
            )}
          </div>
        </div>
      </div>

      <button
        onClick={toggleMockMode}
        className={`fixed bottom-6 right-6 p-4 rounded-full shadow-lg transition-all ${
          mockMode 
            ? 'bg-warn text-base hover:bg-warn/90' 
            : 'bg-panel border-2 border-border text-text hover:bg-panel-hover'
        }`}
        title={mockMode ? 'Disable Mock Mode' : 'Enable Mock Mode'}
        aria-label={mockMode ? 'Disable Mock Mode' : 'Enable Mock Mode'}
      >
        <Settings className={`w-6 h-6 ${mockMode ? 'animate-spin' : ''}`} />
      </button>
      
      {/* Keyboard Shortcuts Help */}
      <KeyboardShortcutsHelp
        isOpen={showShortcutsHelp}
        onClose={() => setShowShortcutsHelp(false)}
      />
      
      {/* Alert Configuration Modal */}
      <AlertConfigModal
        isOpen={showAlertConfig}
        onClose={() => setShowAlertConfig(false)}
      />
      
      {/* Onboarding Modal - H10-01 */}
      <OnboardingModal
        isOpen={showOnboarding}
        onClose={() => setShowOnboarding(false)}
      />

      {/* Glossary Panel - IUI Feature */}
      <GlossaryPanel />
      
      {/* Floating hint - positioned bottom-center to avoid panel interference */}
      {!showShortcutsHelp && !showAlertConfig && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 text-xs text-text-dim">
          Press <kbd className="px-2 py-1 bg-panel border border-border rounded text-text">?</kbd> for shortcuts
          {' | '}
          <kbd className="px-2 py-1 bg-panel border border-border rounded text-text">Ctrl+,</kbd> for alerts
        </div>
      )}
    </div>
  );
}

export default App;
