import { useEffect, useState } from 'react';
import { useWebSocket } from './hooks/useWebSocket';
import { useApi } from './hooks/useApi';
import { useStore } from './context/store';
// Mock data generation removed - now handled by backend
import { useToast } from './context/ToastContext';
import { KeyboardShortcutsHelp, useKeyboardShortcuts } from './components/KeyboardShortcuts';
import MetricsBar from './components/MetricsBar';
import ChatPanel from './components/ChatPanel';
import GraphView from './components/GraphView';
import EventStream from './components/EventStream';
import StatsDashboard from './components/StatsDashboard';
import IncidentPanel from './components/IncidentPanel';
import TopologyView from './components/TopologyView';
import AlertConfigModal from './components/alerts/AlertConfigModal';
import ProactiveSuggestions from './components/ProactiveSuggestions';
import GlossaryPanel from './components/GlossaryPanel';
import { Settings, BarChart3, List, MessageSquare, AlertTriangle, Network } from 'lucide-react';

function App() {
  useWebSocket();
  useApi();
  
  const { mockMode, toggleMockMode, clearOldEvents, filters, setFilters, resetFilters } = useStore();
  const { showInfo } = useToast();
  
  const [showShortcutsHelp, setShowShortcutsHelp] = useState(false);
  const [showAlertConfig, setShowAlertConfig] = useState(false);
  const [activeTab, setActiveTab] = useState<'events' | 'stats' | 'topology'>('events');
  const [leftPanelTab, setLeftPanelTab] = useState<'chat' | 'incidents'>('chat');

  useEffect(() => {
    const interval = setInterval(() => {
      clearOldEvents(10 * 60 * 1000);
    }, 60000);

    return () => clearInterval(interval);
  }, [clearOldEvents]);
  
  // Mock data is now generated by backend - frontend just receives via WebSocket
  
  // Keyboard shortcuts
  useKeyboardShortcuts({
    onShowHelp: () => setShowShortcutsHelp(true),
    onFocusSearch: () => {
      // Focus the search input in FilterBar
      const searchInput = document.querySelector('input[placeholder*="Search"]') as HTMLInputElement;
      if (searchInput) {
        searchInput.focus();
        showInfo('Search focused', 'Start typing to filter events');
      }
    },
    onToggleAnomalies: () => {
      setFilters({ onlyAnomalies: !filters.onlyAnomalies });
      showInfo(
        filters.onlyAnomalies ? 'Showing all events' : 'Showing anomalies only',
        filters.onlyAnomalies ? 'All events visible' : 'Filtered to anomalies only'
      );
    },
    onClearFilters: () => {
      setFilters({ searchQuery: '', severities: [], protocols: [], ports: [], onlyAnomalies: false });
      showInfo('Filters cleared', 'All filters have been removed');
    },
    onResetFilters: () => {
      resetFilters();
      showInfo('Filters reset', 'Filters restored to default');
    },
    onNextEvent: () => {
      showInfo('Next event', 'Use arrow keys to navigate events');
    },
    onPreviousEvent: () => {
      showInfo('Previous event', 'Use arrow keys to navigate events');
    },
    onOpenEvent: () => {
      // This will be handled by EventStream
      showInfo('Open event', 'Click an event to see details');
    },
    onExport: () => {
      // Trigger export menu
      const exportButton = document.querySelector('[aria-label="Export events"]') as HTMLButtonElement;
      if (exportButton) {
        exportButton.click();
      }
    },
    onToggleMockMode: () => {
      toggleMockMode();
      showInfo(
        mockMode ? 'Mock mode disabled' : 'Mock mode enabled',
        mockMode ? 'Connecting to real backend' : 'Generating mock data'
      );
    },
    onOpenSettings: () => {
      // Trigger settings button in MetricsBar
      const settingsButton = document.querySelector('[aria-label="Notification settings"]') as HTMLButtonElement;
      if (settingsButton) {
        settingsButton.click();
      }
    },
    onToggleTab: () => {
      const tabs: Array<'events' | 'stats' | 'topology'> = ['events', 'stats', 'topology'];
      const currentIndex = tabs.indexOf(activeTab);
      const nextTab = tabs[(currentIndex + 1) % tabs.length];
      setActiveTab(nextTab);
      const tabNames = {
        events: 'Events view',
        stats: 'Statistics view',
        topology: 'Topology view'
      };
      showInfo(tabNames[nextTab], `Viewing ${tabNames[nextTab].toLowerCase()}`);
    },
    onToggleLeftPanel: () => {
      setLeftPanelTab(prev => prev === 'chat' ? 'incidents' : 'chat');
      showInfo(
        leftPanelTab === 'chat' ? 'Incidents panel' : 'Chat panel',
        leftPanelTab === 'chat' ? 'Viewing incident management' : 'Viewing AI chat'
      );
    },
    onOpenAlertConfig: () => {
      setShowAlertConfig(true);
      showInfo('Alert Configuration', 'Configure detection settings and rules');
    },
    onShowTopology: () => {
      setActiveTab('topology');
      showInfo('Network Topology', 'Viewing network topology graph');
    },
    isModalOpen: showShortcutsHelp || showAlertConfig,
  });

  return (
    <div className="h-screen flex flex-col bg-base">
      <MetricsBar />

      <div className="flex-1 flex min-h-0">
        <div className="w-[500px] border-r border-border flex flex-col">
          {/* Left Panel Tabs */}
          <div className="flex items-center border-b border-border bg-panel">
            <button
              onClick={() => setLeftPanelTab('chat')}
              className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                leftPanelTab === 'chat'
                  ? 'text-text border-info'
                  : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
              }`}
            >
              <MessageSquare className="w-4 h-4" />
              Chat
            </button>
            <button
              onClick={() => setLeftPanelTab('incidents')}
              className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                leftPanelTab === 'incidents'
                  ? 'text-text border-info'
                  : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
              }`}
            >
              <AlertTriangle className="w-4 h-4" />
              Incidents
            </button>
          </div>
          
          {/* Left Panel Content */}
          {leftPanelTab === 'chat' ? <ChatPanel /> : <IncidentPanel />}
        </div>

        <div className="flex-1 flex flex-col min-w-0">
          {/* Proactive Suggestions - IUI Enhancement */}
          <div className="border-b border-border p-3 bg-panel">
            <ProactiveSuggestions />
          </div>
          
          <div className="h-1/2 border-b border-border">
            <GraphView />
          </div>

          <div className="h-1/2">
            {/* Tab Header */}
            <div className="flex items-center border-b border-border bg-panel">
              <button
                onClick={() => setActiveTab('events')}
                className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                  activeTab === 'events'
                    ? 'text-text border-info'
                    : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
                }`}
              >
                <List className="w-4 h-4" />
                Events
              </button>
              <button
                onClick={() => setActiveTab('stats')}
                className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                  activeTab === 'stats'
                    ? 'text-text border-info'
                    : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
                }`}
              >
                <BarChart3 className="w-4 h-4" />
                Statistics
              </button>
              <button
                onClick={() => setActiveTab('topology')}
                className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                  activeTab === 'topology'
                    ? 'text-text border-info'
                    : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
                }`}
              >
                <Network className="w-4 h-4" />
                Topology
              </button>
            </div>
            
            {/* Tab Content */}
            {activeTab === 'events' ? (
              <EventStream />
            ) : activeTab === 'stats' ? (
              <StatsDashboard />
            ) : (
              <TopologyView />
            )}
          </div>
        </div>
      </div>

      <button
        onClick={toggleMockMode}
        className={`fixed bottom-6 right-6 p-4 rounded-full shadow-lg transition-all ${
          mockMode 
            ? 'bg-warn text-base hover:bg-warn/90' 
            : 'bg-panel border-2 border-border text-text hover:bg-panel-hover'
        }`}
        title={mockMode ? 'Disable Mock Mode' : 'Enable Mock Mode'}
        aria-label={mockMode ? 'Disable Mock Mode' : 'Enable Mock Mode'}
      >
        <Settings className={`w-6 h-6 ${mockMode ? 'animate-spin' : ''}`} />
      </button>
      
      {/* Keyboard Shortcuts Help */}
      <KeyboardShortcutsHelp
        isOpen={showShortcutsHelp}
        onClose={() => setShowShortcutsHelp(false)}
      />
      
      {/* Alert Configuration Modal */}
      <AlertConfigModal
        isOpen={showAlertConfig}
        onClose={() => setShowAlertConfig(false)}
      />

      {/* Glossary Panel - IUI Feature */}
      <GlossaryPanel />
      
      {/* Floating hint */}
      {!showShortcutsHelp && !showAlertConfig && (
        <div className="fixed bottom-6 left-6 text-xs text-text-dim">
          Press <kbd className="px-2 py-1 bg-panel border border-border rounded text-text">?</kbd> for shortcuts
          {' | '}
          <kbd className="px-2 py-1 bg-panel border border-border rounded text-text">Ctrl+,</kbd> for alerts
        </div>
      )}
    </div>
  );
}

export default App;
