import { useEffect, useState, useRef } from 'react';
import { useWebSocket } from './hooks/useWebSocket';
import { useApi } from './hooks/useApi';
import { useStore } from './context/store';
// Mock data generation removed - now handled by backend
import { useToast } from './context/ToastContext';
import { KeyboardShortcutsHelp, useKeyboardShortcuts } from './components/shared/KeyboardShortcuts';
import { MetricsBar, ChatPanel, TopologyView, StatsDashboard } from './components/core';
import { GraphView, EventStream } from './components/events';
import { IncidentPanel } from './components/panels';
import AlertConfigModal from './components/alerts/AlertConfigModal';
import { ProactiveSuggestions } from './components/panels';
import { GlossaryPanel } from './components/panels';
import ThreeDTopologyModal from './components/ThreeDTopologyModal';
import OnboardingModal from './components/modals/OnboardingModal';
import UserProfileModal from './components/modals/UserProfileModal';
import PacketFlowIntro from './components/modals/PacketFlowIntro';
import SUSurveyModal from './components/modals/SUSurveyModal';
import { Settings, BarChart3, List, MessageSquare, AlertTriangle, Network, Box } from 'lucide-react';

function App() {
  const { reconnect } = useWebSocket();
  useApi();
  
  const { clearOldEvents, filters, setFilters, resetFilters, userProfile } = useStore();
  const { showInfo } = useToast();
  
  const [showShortcutsHelp, setShowShortcutsHelp] = useState(false);
  const [showAlertConfig, setShowAlertConfig] = useState(false);
  const [show3DTopology, setShow3DTopology] = useState(false);
  const [showOnboarding, setShowOnboarding] = useState(!userProfile.onboarding_completed);
  const [showUserProfile, setShowUserProfile] = useState(false);
  const [showPacketFlowIntro, setShowPacketFlowIntro] = useState(false);
  const [showSUSurvey, setShowSUSurvey] = useState(false);
  const [showGlossary, setShowGlossary] = useState(false);
  const [leftPanelCollapsed, setLeftPanelCollapsed] = useState(false);
  const [leftPanelWidth, setLeftPanelWidth] = useState(500);
  const [activeTab, setActiveTab] = useState<'events' | 'stats' | 'topology'>('events');
  const [leftPanelTab, setLeftPanelTab] = useState<'chat' | 'incidents'>('chat');
  const [graphCollapsed, setGraphCollapsed] = useState(false);
  
  // Drag reference for resizing
  const isDraggingRef = useRef(false);

  useEffect(() => {
    const interval = setInterval(() => {
      clearOldEvents(10 * 60 * 1000);
    }, 60000);

    return () => clearInterval(interval);
  }, [clearOldEvents]);

  // Show SUS survey after 50 interactions (if not completed recently)
  useEffect(() => {
    const lastSurvey = userProfile.usability_metrics?.sus_surveys?.[userProfile.usability_metrics.sus_surveys.length - 1];
    const daysSinceLastSurvey = lastSurvey 
      ? (Date.now() - new Date(lastSurvey.timestamp).getTime()) / (1000 * 60 * 60 * 24)
      : Infinity;
    
    // Show survey if: 50+ interactions AND (no previous survey OR 7+ days since last survey)
    if (userProfile.interaction_count >= 50 && daysSinceLastSurvey >= 7) {
      const timer = setTimeout(() => {
        setShowSUSurvey(true);
      }, 5000); // Show after 5 seconds
      return () => clearTimeout(timer);
    }
  }, [userProfile.interaction_count]);

  // Handle left panel resize
  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (!isDraggingRef.current) return;
      const newWidth = Math.max(300, Math.min(800, e.clientX));
      setLeftPanelWidth(newWidth);
    };

    const handleMouseUp = () => {
      isDraggingRef.current = false;
    };

    document.addEventListener('mousemove', handleMouseMove);
    document.addEventListener('mouseup', handleMouseUp);
    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
    };
  }, []);
  
  // Mock data is now generated by backend - frontend just receives via WebSocket
  
  // Keyboard shortcuts
  useKeyboardShortcuts({
    onShowHelp: () => setShowShortcutsHelp(true),
    onFocusSearch: () => {
      // Focus the search input in FilterBar
      const searchInput = document.querySelector('input[placeholder*="Search"]') as HTMLInputElement;
      if (searchInput) {
        searchInput.focus();
        showInfo('Search focused', 'Start typing to filter events');
      }
    },
    onToggleAnomalies: () => {
      setFilters({ onlyAnomalies: !filters.onlyAnomalies });
      showInfo(
        filters.onlyAnomalies ? 'Showing all events' : 'Showing anomalies only',
        filters.onlyAnomalies ? 'All events visible' : 'Filtered to anomalies only'
      );
    },
    onClearFilters: () => {
      setFilters({ searchQuery: '', severities: [], protocols: [], ports: [], onlyAnomalies: false });
      showInfo('Filters cleared', 'All filters have been removed');
    },
    onResetFilters: () => {
      resetFilters();
      showInfo('Filters reset', 'Filters restored to default');
    },
    onNextEvent: () => {
      showInfo('Next event', 'Use arrow keys to navigate events');
    },
    onPreviousEvent: () => {
      showInfo('Previous event', 'Use arrow keys to navigate events');
    },
    onOpenEvent: () => {
      // This will be handled by EventStream
      showInfo('Open event', 'Click an event to see details');
    },
    onExport: () => {
      // Trigger export menu
      const exportButton = document.querySelector('[aria-label="Export events"]') as HTMLButtonElement;
      if (exportButton) {
        exportButton.click();
      }
    },
    onOpenSettings: () => {
      // Trigger settings button in MetricsBar
      const settingsButton = document.querySelector('[aria-label="Notification settings"]') as HTMLButtonElement;
      if (settingsButton) {
        settingsButton.click();
      }
    },
    onToggleTab: () => {
      const tabs: Array<'events' | 'stats' | 'topology'> = ['events', 'stats', 'topology'];
      const currentIndex = tabs.indexOf(activeTab);
      const nextTab = tabs[(currentIndex + 1) % tabs.length];
      setActiveTab(nextTab);
      const tabNames = {
        events: 'Events view',
        stats: 'Statistics view',
        topology: 'Topology view'
      };
      showInfo(tabNames[nextTab], `Viewing ${tabNames[nextTab].toLowerCase()}`);
    },
    onToggleLeftPanel: () => {
      setLeftPanelTab(prev => prev === 'chat' ? 'incidents' : 'chat');
      showInfo(
        leftPanelTab === 'chat' ? 'Incidents panel' : 'Chat panel',
        leftPanelTab === 'chat' ? 'Viewing incident management' : 'Viewing AI chat'
      );
    },
    onOpenAlertConfig: () => {
      setShowAlertConfig(true);
      showInfo('Alert Configuration', 'Configure detection settings and rules');
    },
    onShowTopology: () => {
      setActiveTab('topology');
      showInfo('Network Topology', 'Viewing network topology graph');
    },
    onShow3DTopology: () => {
      setShow3DTopology(true);
      showInfo('3D Network Topology', 'Opening immersive 3D view (Escape to close)');
    },
    onOpenUserProfile: () => {
      setShowUserProfile(true);
      showInfo('User Profile', 'View and manage your preferences');
    },
    isModalOpen: showShortcutsHelp || showAlertConfig || show3DTopology || showOnboarding || showUserProfile || showSUSurvey,
  });

  return (
    <div className="h-screen flex flex-col bg-base">
      <MetricsBar 
        onShowHelp={() => setShowShortcutsHelp(true)}
        onOpenUserProfile={() => setShowUserProfile(true)}
        onReconnect={reconnect}
        onOpenAlertConfig={() => setShowAlertConfig(true)}
      />

      <div className="flex-1 flex min-h-0">
        {/* Left Panel - Collapsible & Resizable */}
        {!leftPanelCollapsed && (
          <>
            <div style={{ width: `${leftPanelWidth}px` }} className="border-r border-border flex flex-col min-w-0 overflow-hidden">
              {/* Left Panel Tabs */}
              <div className="flex items-center border-b border-border bg-panel flex-shrink-0">
                <button
                  onClick={() => setLeftPanelTab('chat')}
                  className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                    leftPanelTab === 'chat'
                      ? 'text-text border-info'
                      : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
                  }`}
                >
                  <MessageSquare className="w-4 h-4" />
                  Chat
                </button>
                <button
                  onClick={() => setLeftPanelTab('incidents')}
                  className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                    leftPanelTab === 'incidents'
                      ? 'text-text border-info'
                      : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
                  }`}
                >
                  <AlertTriangle className="w-4 h-4" />
                  Incidents
                </button>
                <button
                  onClick={() => setLeftPanelCollapsed(true)}
                  className="ml-auto p-2 text-text-dim hover:text-text transition-colors flex-shrink-0"
                  title="Collapse panel"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                  </svg>
                </button>
              </div>
              
              {/* Left Panel Content - Scrollable */}
              <div className="flex-1 overflow-y-auto overflow-x-hidden">
                {leftPanelTab === 'chat' ? <ChatPanel /> : <IncidentPanel />}
              </div>
            </div>

            {/* Resize Handle */}
            <div
              onMouseDown={(e) => {
                e.preventDefault();
                isDraggingRef.current = true;
              }}
              className="w-1.5 bg-border hover:bg-info cursor-col-resize transition-colors active:bg-info"
              title="Drag to resize panel"
              style={{ userSelect: 'none' }}
            />
          </>
        )}

        {/* Collapse/Expand Button */}
        {leftPanelCollapsed && (
          <button
            onClick={() => setLeftPanelCollapsed(false)}
            className="px-2 py-4 text-text-dim hover:text-text bg-panel border-r border-border transition-colors"
            title="Expand panel"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
            </svg>
          </button>
        )}

        <div className="flex-1 flex flex-col min-w-0">
          <div className={`${graphCollapsed ? 'h-20' : 'h-[35vh]'} border-b border-border transition-all duration-300`}>
            <GraphView onCollapseChange={setGraphCollapsed} />
          </div>

          <div className="flex-1">
            {/* Tab Header */}
            <div className="flex items-center border-b border-border bg-panel">
              <button
                onClick={() => setActiveTab('events')}
                className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                  activeTab === 'events'
                    ? 'text-text border-info'
                    : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
                }`}
              >
                <List className="w-4 h-4" />
                Events
              </button>
              <button
                onClick={() => setActiveTab('stats')}
                className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                  activeTab === 'stats'
                    ? 'text-text border-info'
                    : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
                }`}
              >
                <BarChart3 className="w-4 h-4" />
                Statistics
              </button>
              <button
                onClick={() => setActiveTab('topology')}
                className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 ${
                  activeTab === 'topology'
                    ? 'text-text border-info'
                    : 'text-text-dim border-transparent hover:text-text hover:bg-panel-hover'
                }`}
              >
                <Network className="w-4 h-4" />
                Topology
              </button>
              <button
                onClick={() => setShow3DTopology(true)}
                className="flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors border-b-2 border-transparent text-text-dim hover:text-text hover:bg-panel-hover"
                title="Open 3D immersive network view (Ctrl+Shift+3)"
              >
                <Box className="w-4 h-4" />
                3D View
              </button>
            </div>
            
            {/* Tab Content */}
            {activeTab === 'events' ? (
              <EventStream />
            ) : activeTab === 'stats' ? (
              <StatsDashboard />
            ) : (
              <TopologyView />
            )}
          </div>
        </div>
      </div>
      
      {/* Intro Animation - Only show on first app load */}
      {showPacketFlowIntro && (
        <PacketFlowIntro onComplete={() => setShowPacketFlowIntro(false)} />
      )}
      
      {/* Onboarding Modal - IUI Feature */}
      <OnboardingModal
        isOpen={showOnboarding}
        onClose={() => setShowOnboarding(false)}
      />
      
      {/* User Profile Modal - IUI Feature */}
      <UserProfileModal
        isOpen={showUserProfile}
        onClose={() => setShowUserProfile(false)}
      />

      {/* SUS Survey Modal - Usability Feedback */}
      <SUSurveyModal
        isOpen={showSUSurvey}
        onClose={() => setShowSUSurvey(false)}
      />
      
      {/* Keyboard Shortcuts Help */}
      <KeyboardShortcutsHelp
        isOpen={showShortcutsHelp}
        onClose={() => setShowShortcutsHelp(false)}
      />
      
      {/* Alert Configuration Modal */}
      <AlertConfigModal
        isOpen={showAlertConfig}
        onClose={() => setShowAlertConfig(false)}
      />

      {/* 3D Topology Modal */}
      <ThreeDTopologyModal
        isOpen={show3DTopology}
        onClose={() => setShow3DTopology(false)}
      />

      {/* Glossary Panel - Modal */}
      {showGlossary && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-panel border border-border rounded-lg shadow-xl max-w-2xl w-full max-h-[80vh] overflow-hidden flex flex-col">
            <div className="flex items-center justify-between p-4 border-b border-border">
              <h2 className="text-lg font-semibold text-text">Glossary</h2>
              <button
                onClick={() => setShowGlossary(false)}
                className="p-1 text-text-dim hover:text-text transition-colors"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="flex-1 overflow-y-auto">
              <GlossaryPanel />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
